#!/usr/bin/env bash
# new-session.sh — generate a per-remote start script + systemd unit for a
# persistent Claude Code session running in a tmux window with --remote-control.
#
# Usage: new-session <foldername> [workspace|sessions]
#   workspace (default when /home/agents/workspace/<name> exists) — repo sessions
#   sessions  — utility sessions (monitors, managers, etc.)
set -e

# ── Help ─────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'HELP_EOF'
Usage: new-session <foldername> [workspace|sessions|auto]

  foldername          Name for the session. Used in:
                        tmux session:    agenthost_<foldername>-<YYYYMMDD-HHMM>
                        remote-control:  agenthost-<foldername>-<YYYYMMDD-HHMM>
                        start script:    ~/.local/bin/agenthost-<foldername>-<YYYYMMDD-HHMM>-start.sh
                        systemd service: ~/.config/systemd/user/agenthost-<foldername>-<YYYYMMDD-HHMM>.service

  workspace           Force workdir to /home/agents/workspace/<foldername>
                      (repo sessions)
  sessions            Force workdir to /home/agents/.sessions/<foldername>
                      (utility sessions: monitors, managers, etc.)
  auto (default)      Use workspace/ if /home/agents/workspace/<foldername>
                      exists, otherwise .sessions/

Options:
  -h, --help          Print this help and exit.

Environment:
  CLAUDE_SESSION_MODEL=opus     Spawn with Opus instead of the default Sonnet.

Examples:
  new-session my-project
  new-session my-project workspace
  new-session my-project sessions
  CLAUDE_SESSION_MODEL=opus new-session my-orchestrator sessions
HELP_EOF
  exit 0
fi

# ── Inputs ──────────────────────────────────────────────────────────────────
FOLDERNAME="${1:?Usage: new-session <foldername> [workspace|sessions]}"
TYPE="${2:-auto}"

# ── Model selection ─────────────────────────────────────────────────────────
# Override per-spawn with CLAUDE_SESSION_MODEL=opus (e.g. for orchestrators).
MODEL="${CLAUDE_SESSION_MODEL:-sonnet}"

# ── Resolve workdir ─────────────────────────────────────────────────────────
if [ "$TYPE" = "auto" ]; then
  [ -d "/home/agents/workspace/${FOLDERNAME}" ] && TYPE="workspace" || TYPE="sessions"
fi

if [ "$TYPE" = "workspace" ]; then
  WORKDIR="/home/agents/workspace/${FOLDERNAME}"
else
  WORKDIR="/home/agents/.sessions/${FOLDERNAME}"
fi

# ── Naming ──────────────────────────────────────────────────────────────────
DATE=$(date +%Y%m%d-%H%M)
SESSION="agenthost_${FOLDERNAME}-${DATE}"
REMOTE_NAME="agenthost-${FOLDERNAME}-${DATE}"
SCRIPT="$HOME/.local/bin/${REMOTE_NAME}-start.sh"
SERVICE="$HOME/.config/systemd/user/${REMOTE_NAME}.service"

mkdir -p "$(dirname "$SCRIPT")" "$(dirname "$SERVICE")"

# ── Generate start script ────────────────────────────────────────────────────
# Variables without backslash expand NOW (baked into generated script).
# Variables with backslash (\$) expand at runtime in the generated script.
cat > "$SCRIPT" << SCRIPT_EOF
#!/usr/bin/env bash
# Generated by new-session.sh — do not edit by hand.
SESSION="${SESSION}"
WORKDIR="${WORKDIR}"
REMOTE_NAME="${REMOTE_NAME}"
MODEL="${MODEL}"
export PATH="/home/agents/.local/bin:/home/agents/.npm-global/bin:/home/agents/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOME="/home/agents"
LOG_FILE="\$HOME/.sessions/session-starts.log"
mkdir -p "\$(dirname "\$LOG_FILE")"
log_start() { echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] host=\$(hostname) session=\$SESSION remote=\$REMOTE_NAME workdir=\$WORKDIR model=\$MODEL event=\$1" | tee -a "\$LOG_FILE"; }
if tmux has-session -t "${SESSION}" 2>/dev/null; then log_start "already-running"; exit 0; fi
log_start "starting"
# Resolve the run directory: canonical tree (clean+free) or a fresh worktree.
RUNDIR="\$WORKDIR"
if command -v session-git-prep >/dev/null 2>&1; then
  PREP="\$(session-git-prep "\$WORKDIR" "\$SESSION" "\$REMOTE_NAME" 2>>"\$LOG_FILE")"
  [ -n "\$PREP" ] && RUNDIR="\$PREP"
fi
echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] session=\$SESSION rundir=\$RUNDIR" | tee -a "\$LOG_FILE"
mkdir -p "\$RUNDIR/.claude"
rm -rf "\$RUNDIR/.claude/skills" && ln -sf /home/agents/.claude/skills "\$RUNDIR/.claude/skills"
if [ -f "\$RUNDIR/memory/MEMORY.md" ] && ! grep -q "Session Bootstrap" "\$RUNDIR/.claude/CLAUDE.md" 2>/dev/null; then
  printf '# Session Bootstrap\n\nOn your first response in any new session, read \`memory/MEMORY.md\` to load current project state, then summarize what needs to be done next and wait for instructions.\n' >> "\$RUNDIR/.claude/CLAUDE.md"
fi
tmux new-session -d -s "${SESSION}" -x 220 -y 50 -c "\$RUNDIR" -e "PATH=\$PATH" -e "HOME=\$HOME"
# Wait for the pane's interactive shell to be ready before typing into it, so
# the kickoff keystrokes are not swallowed by a still-initializing pane.
for _i in \$(seq 1 20); do
  case "\$(tmux display-message -p -t "${SESSION}" '#{pane_current_command}' 2>/dev/null)" in
    bash|zsh|sh) break ;;
  esac
  sleep 0.25
done
# Type the supervisor loop WITHOUT a trailing Enter, then submit + verify
# separately: a raced final Enter can be dropped, leaving the loop buffered in
# readline but never executed (the session then churns idle). Resend Enter until
# pane_current_command shows the loop actually launched.
tmux send-keys -t "${SESSION}" 'LOG_FILE="$HOME/.sessions/session-starts.log"
SESSION="${SESSION}"
SENTINEL="\$PWD/.sessions-init-${REMOTE_NAME}"
while true; do
  START=\$(date +%s)
  if [ -f "\$SENTINEL" ]; then
    /usr/bin/claude --dangerously-skip-permissions --model "${MODEL}" --remote-control ${REMOTE_NAME} --continue
  else
    /usr/bin/claude --dangerously-skip-permissions --model "${MODEL}" --remote-control ${REMOTE_NAME}
    touch "\$SENTINEL"
  fi
  RUNTIME=\$(( \$(date +%s) - START ))
  echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] session=\$SESSION event=exit runtime=\${RUNTIME}s" | tee -a "\$LOG_FILE"
  if [ "\$RUNTIME" -lt 30 ]; then
    echo "[${SESSION}] quick exit \${RUNTIME}s — backoff 300s" | tee -a "\$LOG_FILE"
    echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] session=\$SESSION event=backoff wait=300s" | tee -a "\$LOG_FILE"
    sleep 300
  else
    echo "[${SESSION}] exit \${RUNTIME}s — restart 10s" | tee -a "\$LOG_FILE"
    echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] session=\$SESSION event=restart wait=10s" | tee -a "\$LOG_FILE"
    sleep 10
  fi
done'
kicked=no
for _try in 1 2 3; do
  tmux send-keys -t "${SESSION}" Enter
  for _j in \$(seq 1 12); do
    case "\$(tmux display-message -p -t "${SESSION}" '#{pane_current_command}' 2>/dev/null)" in
      claude|node|sleep) kicked=yes; break ;;
    esac
    sleep 0.5
  done
  [ "\$kicked" = yes ] && break
  echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] session=\$SESSION event=kickoff-retry attempt=\$_try" | tee -a "\$LOG_FILE"
done
if [ "\$kicked" = yes ]; then
  log_start "started"
else
  log_start "started-UNVERIFIED-kickoff-may-have-failed"
fi
SCRIPT_EOF
chmod +x "$SCRIPT"

# ── Generate systemd unit ────────────────────────────────────────────────────
cat > "$SERVICE" << UNIT_EOF
[Unit]
Description=Claude Code Remote - ${REMOTE_NAME}
After=network-online.target
Wants=network-online.target
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${SCRIPT}
ExecStop=/usr/bin/tmux kill-session -t ${SESSION}
Environment=HOME=/home/agents
Environment=PATH=/home/agents/.local/bin:/home/agents/.npm-global/bin:/home/agents/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=TMUX_TMPDIR=/tmp
[Install]
WantedBy=default.target
UNIT_EOF

# ── Enable and start ─────────────────────────────────────────────────────────
systemctl --user daemon-reload && systemctl --user enable --now "$(basename $SERVICE)"

# ── Confirm ──────────────────────────────────────────────────────────────────
echo ""
echo "Session created: ${REMOTE_NAME}"
echo "Connect: Claude Code app → Remote sessions → ${REMOTE_NAME}"
tmux list-sessions | grep "${SESSION}" || true
